#!/usr/bin/env python3
"""Step 3. Pull still frames from the video so the agent can LOOK at candidate moments.

What it does
  1. For each time you give, saves one JPG frame to episodes/<ep>/frames/.
  2. Builds frames/contact_sheet.jpg: a grid of all frames with the time
     stamped on each tile. One image the agent can open with view_image.

Use it to check: is the speaker on camera, is the face expressive, is the
framing clean, is there a glitch, is this a good thumbnail frame.

Usage
  python3 scripts/frames.py episodes/ep05/episode.mp4 12:34 18:02.5 00:41:10
  python3 scripts/frames.py episodes/ep05/episode.mp4 --every 60      # one frame per minute
  python3 scripts/frames.py episodes/ep05/episode.mp4 --range 12:30 12:58 --step 2
"""

import argparse
import io
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import (SafeParser, FF_IN, FF_IN_IMG, IMG_OUT, check_source, commit_target, find_font, fmt_mmss, fmt_time,  # noqa: E402
                     media_path, output_dir, parse_time, probe, require_tool, run_writing, show, temp_target,
                     utf8_stdout, write_bytes_safely)

FRAME_LIMIT = 80
FONT_CANDIDATES = ["DejaVuSans-Bold.ttf", "arialbd.ttf", "Arial Bold.ttf", "LiberationSans-Bold.ttf"]


def bounded_int(lo, hi):
    """argparse type factory: a whole number from lo to hi."""
    def parse(text):
        try:
            v = int(text)
        except ValueError:
            raise argparse.ArgumentTypeError("%r is not a whole number" % text)
        if not lo <= v <= hi:
            raise argparse.ArgumentTypeError("must be from %d to %d" % (lo, hi))
        return v
    return parse


positive_int = bounded_int(1, 10 ** 9)
width_arg = bounded_int(160, 1920)  # a tile wider than 1080p is never needed to judge a frame
cols_arg = bounded_int(1, 10)
SHEET_MAX_PIXELS = 30_000_000       # tiles and sheet are both live: about 180 MB of RGB at the very most


def tile_size(width, height, tile_w):
    """Tile dimensions when the longer side is scaled to tile_w, both even for the encoder."""
    if width >= height:
        tw, th = tile_w, round(tile_w * height / width)
    else:
        tw, th = round(tile_w * width / height), tile_w
    return max(2, tw - tw % 2), max(2, th - th % 2)


def check_budget(n, tw, th):
    """Refuse before the first frame is written when the tiles would not fit in memory."""
    if n * tw * th > SHEET_MAX_PIXELS:
        raise ValueError("%d frames at %dx%d is %d megapixels; the limit is %d. Lower --width or take fewer frames." % (
            n, tw, th, n * tw * th // 1_000_000, SHEET_MAX_PIXELS // 1_000_000))


def build_times(explicit, duration, every=None, rng=None, step=2.0, limit=FRAME_LIMIT):
    """Turn the requested times into a sorted list of distinct times inside the video.

    Counts before building anything and refuses past the limit. Times are clamped to the
    video first and generated by index, never by accumulating floats: for a large enough
    start, t + step == t and an accumulating loop never ends.
    """
    times = [parse_time(t) for t in explicit]
    try:
        if every is not None:
            if every <= 0:
                raise ValueError("--every must be a positive number of seconds")
            n = int(duration / every) + 1
            if n > limit:
                raise ValueError("--every %g over %.0f s is about %d frames. Keep it under %d per sheet." % (
                    every, duration, n, limit))
            times += [i * every for i in range(n) if i * every < duration]
        if rng:
            a, b = parse_time(rng[0]), parse_time(rng[1])
            if step <= 0:
                raise ValueError("--step must be a positive number of seconds")
            if b < a:
                raise ValueError("--range end is before its start")
            a, b = min(a, duration), min(b, duration)
            n = int((b - a) / step + 1e-9) + 1
            if n > limit:
                raise ValueError("--range with --step %g is about %d frames. Keep it under %d per sheet." % (
                    step, n, limit))
            times += [a + i * step for i in range(n)]
    except OverflowError:
        raise ValueError("--every and --step must be sensible numbers of seconds")
    if not times:
        raise ValueError("Give at least one time, or --every, or --range.")
    times = sorted({round(min(max(t, 0.0), max(duration - 0.05, 0.0)), 3) for t in times})
    if len(times) > limit:
        raise ValueError("That is %d frames. Keep it under %d per sheet (use a larger --every or --step)." % (
            len(times), limit))
    return times


def grab(video, t, out_path, tw, th):
    tmp = temp_target(out_path)
    run_writing(["ffmpeg", "-y", "-v", "error", "-ss", "%.3f" % t, *FF_IN, "-i", media_path(video), "-frames:v", "1",
                 "-vf", "scale=%d:%d" % (tw, th), "-q:v", "3", *IMG_OUT, str(tmp)], tmp)
    commit_target(tmp, out_path)


def contact_sheet(frames, times, out_path, cols=4, expect=None):
    """Tile the frames into one image. `expect` is the (w, h) every tile must have; a tile
    that grew between the grab and the sheet is not ours and is refused."""
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        # Fallback: ffmpeg tile filter, no labels.
        n = len(frames)
        rows = (n + cols - 1) // cols
        inputs = []
        for f in frames:
            inputs += [*FF_IN_IMG, "-i", media_path(f)]
        filt = "".join("[%d:v]" % i for i in range(n)) + "concat=n=%d:v=1:a=0,tile=%dx%d" % (n, cols, rows)
        tmp = temp_target(out_path)
        run_writing(["ffmpeg", "-y", "-v", "error"] + inputs + ["-filter_complex", filt, "-frames:v", "1",
                     *IMG_OUT, str(tmp)], tmp)
        commit_target(tmp, out_path)
        return "ffmpeg (no time labels; install Pillow for labels: python3 -m pip install pillow)"

    tiles = []
    for f in frames:
        try:
            im = Image.open(f, formats=["JPEG"])
        except (OSError, ValueError, Image.DecompressionBombError):
            raise ValueError("%s is not the JPEG tile this script wrote" % show(f))
        with im:
            if expect and (im.width > expect[0] + 2 or im.height > expect[1] + 2):
                raise ValueError("%s is %dx%d, larger than the tile this script wrote" % (show(f), im.width, im.height))
            tiles.append(im.convert("RGB"))
    tw, th = tiles[0].size
    rows = (len(tiles) + cols - 1) // cols
    check_budget(rows * cols, tw, th)
    sheet = Image.new("RGB", (cols * tw, rows * th), (20, 20, 20))
    draw = ImageDraw.Draw(sheet)
    font_path = find_font(FONT_CANDIDATES)
    try:
        font = ImageFont.truetype(font_path, 28) if font_path else ImageFont.load_default()
    except OSError:
        font = ImageFont.load_default()
    for i, (tile, t) in enumerate(zip(tiles, times)):
        x = (i % cols) * tw
        y = (i // cols) * th
        sheet.paste(tile, (x, y))
        label = fmt_mmss(t)
        draw.rectangle([x, y, x + 120, y + 40], fill=(0, 0, 0))
        draw.text((x + 8, y + 5), label, fill=(255, 230, 0), font=font)
    buf = io.BytesIO()
    sheet.save(buf, format="JPEG", quality=85)  # in memory first: a failed save leaves no file
    write_bytes_safely(out_path, buf.getvalue())
    return "Pillow"


def main():
    ap = SafeParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("video")
    ap.add_argument("times", nargs="*", help="times like 12:34, 00:12:34.5, or 754.5")
    ap.add_argument("--every", type=float, help="grab one frame every N seconds across the whole video")
    ap.add_argument("--range", nargs=2, metavar=("START", "END"), help="grab frames between two times")
    ap.add_argument("--step", type=float, default=2.0, help="seconds between frames when using --range")
    ap.add_argument("--width", type=width_arg, default=640, help="tile width in pixels, 160 to 1920")
    ap.add_argument("--cols", type=cols_arg, default=4, help="tiles per row, 1 to 10")
    args = ap.parse_args()
    utf8_stdout()

    require_tool("ffmpeg")
    video = Path(args.video)
    if not video.exists():
        sys.exit("File not found: %s" % show(video))
    info = probe(video)
    duration = info["duration"]

    try:
        times = build_times(args.times, duration, every=args.every, rng=args.range, step=args.step)
    except ValueError as exc:
        sys.exit(str(exc))

    try:
        check_source(info["width"], info["height"])
        tw, th = tile_size(info["width"], info["height"], args.width)
        check_budget(len(times), tw, th)
        out_dir = output_dir(video, "frames")
        frames = []
        for t in times:
            name = "f_%s.jpg" % fmt_time(t).replace(":", "-")
            p = out_dir / name
            grab(video, t, p, tw, th)
            frames.append(p)
            print("frame %s -> %s" % (fmt_mmss(t), show(p)))
        sheet = out_dir / "contact_sheet.jpg"
        how = contact_sheet(frames, times, sheet, args.cols, (tw, th))
    except (OSError, ValueError) as exc:
        sys.exit(str(exc))
    print("WROTE %s (%s). Open it with view_image to inspect." % (show(sheet), how))


if __name__ == "__main__":
    main()
